SOURCES=\
	src/FileReader.cpp\
	src/MolSim.cpp\
	src/outputWriter/vtk-unstructured.cpp\
	src/outputWriter/VTKWriter.cpp\
	src/outputWriter/XYZWriter.cpp\
	src/Particle.cpp\
	src/utils/Settings.cpp\
	src/Simulator.cpp\
	src/ParticleContainer.cpp\
	src/CellListContainer.cpp\
	src/ScenarioFactory.cpp\
	src/utils/MaxwellBoltzmannDistribution.cpp\
	src/utils/ParticleGenerator.cpp\
	src/utils/SimulationConfig.cpp\
	src/outputWriter/RenderOutputWriter.cpp\
	src/utils/Thermostat.cpp\
	src/utils/Matrix.cpp\
	src/JobQueue.cpp\
	src/utils/ThermostatDiscrete.cpp\
	src/SimulationJobQueue.cpp\
	src/APCJobQueue.cpp\
	src/utils/PapiEnv.cpp
