SOURCES=\
	src/FileReader.cpp\
	src/MolSim.cpp\
	src/outputWriter/vtk-unstructured.cpp\
	src/outputWriter/VTKWriter.cpp\
	src/outputWriter/XYZWriter.cpp\
	src/Particle.cpp\
	src/utils/Settings.cpp\
	src/Simulator.cpp\
	src/ParticleContainer.cpp\
	src/ScenarioFactory.cpp\
	src/utils/MaxwellBoltzmannDistribution.cpp\
	src/utils/ParticleGenerator.cpp\
